### ISSUE TITLE
Comment doesn't get published

### ISSUE THREAD

**Issue by ArthurNRL** [py-cov-action/python-coverage-comment-action#169]
Hey it's me again 😦 

Now the action is creating the branch and updating it when in "default branch mode". But when run in a PR it doens't publish a comment at all.
Here's my jobs definition
```
# .github/workflows/build.yml
name: build/test
on: push

jobs:
  test:
    name: Test
    needs: install
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get virtualenv
        uses: ./.github/actions/get_venv

      - name: Test with pytest
        run: |
          ./venv/Scripts/activate.ps1
          pytest --cov alteryx_xml_tool --cov-report term-missing --cov-report html --durations 10

      - name: Store coverage file
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: .coverage

  coverage:
    # must run with linux
    name: Coverage
    runs-on: ubuntu-latest
    needs: test
    permissions:
        contents: write
        pull-requests: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        id: download
        with:
          name: coverage
          path: .

      - name: Coverage comment
        id: coverage_comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Store Pull Request comment to be posted
        uses: actions/upload-artifact@v3
        if: steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true'
        with:
          name: python-coverage-comment-action
          path: python-coverage-comment-action.txt
```
```
#.github/workflows/coverage.yml
name: Post coverage comment

on:
  workflow_run:
    workflows: ["build/test"]
    types:
      - completed

jobs:
  test:
    name: Run tests & display coverage
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    permissions:
      # Gives the action the necessary permissions for publishing new
      # comments in pull requests.
      pull-requests: write
      # Gives the action the necessary permissions for editing existing
      # comments (to avoid publishing multiple comments in the same PR)
      contents: write
      # Gives the action the necessary permissions for looking up the
      # workflow that launched this workflow, and download the related
      # artifact that contains the comment to be published
      actions: read
    steps:
      # DO NOT run actions/checkout here, for security reasons
      # For details, refer to https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
      - name: Post comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PR_RUN_ID: ${{ github.event.workflow_run.id }}
          # Update those if you changed the default values:
          # COMMENT_ARTIFACT_NAME: python-coverage-comment-action
          # COMMENT_FILENAME: python-coverage-comment-action.txt
```

The thing is the store comment step gets skipped in both pr/default branch mode
![image](https://user-images.githubusercontent.com/63674393/236244049-9b9e837e-2857-4151-83a0-fa7521454fa9.png)
and so does the coverage.yml workflow
![image](https://user-images.githubusercontent.com/63674393/236244374-58a98d55-12fe-410e-aa33-f88ec70c29e8.png)

**Comment by kieferro** [comment]
I would guess that it is because of your definition of the trigger events for the action. You're actually only supposed to use `push` as a trigger when pushing to the branch for which the coverage data is collected.
I suspect you are using internal PRs that also trigger the action because they push to other branches. But the problem with that is that the action differentiates whether it is in PR mode or branch mode by the event trigger. If branch mode is triggered for a non-default branch, then simply nothing happens.
So you need to change your trigger definition a bit to something like:
```yml
# .github/workflows/build.yml
name: build/test

on:
  pull_request:
  push:
    branches:
      - 'main'
```
That way, the action should understands that it's about a PR and not a push event.
