### ISSUE TITLE
Check for open PRs on `push` GHA trigger

### ISSUE THREAD

**Issue by jarojasm95** [py-cov-action/python-coverage-comment-action#234]
Hello 👋 

I've been successfully using this action for a couple weeks now (it is great 👏 ) - I am opening this issue to suggest an improvement:

When the action is run as part of a `push` it would be great if the action could lookup the open PR that the commit belongs to and post the PR comment there.

I think this could simplify the usage of this action by obviating the need for:
- `pull_request` trigger
- `actions/upload-artifact@v3`
- `workflow_run` trigger

(I am not suggesting that the above functionality is removed, only suggesting that we improve the `push` event handling for now, which could make this action easier to use imo)

What do you think? If this sounds like an acceptable improvement I would also be willing to work on it 🙂

**Comment by ewjoachim** [comment]
Hm, I could be wrong, but either you plan for only people who have write access to the repo to contribute, in which case you [don't need](https://github.com/py-cov-action/python-coverage-comment-action#basic-usage-without-external-contributors) the upload-artifact action and the workflow_run, or you plan for external people to contribute, and they won't be able to trigger the `push` action, would they ?

The only setup where this would help if I understand correctly would be if you only have write-access contributors, and have only set up your CI for `push` whatever the branch is and the CI would be the same otherwise whether we push to `main` or `feature_branch_x` so you'd like to plug the action as-is and let it determine if we should run in "default branch" mode or "PR" mode ?

**Comment by jarojasm95** [comment]
> So if I understand correctly everything, you'd like to avoid doing the change above, and instead for the action to support PR mode on push. Right ?

This is correct 👍 

I would like to avoid adding `pull_request` trigger to my existing workflow primarily because that workflow takes a significant amount of time to complete, and having both triggers means that the workflow runs twice for new commits added to an open pull request

**Comment by jarojasm95** [comment]
Maybe also helpful context:

The repository where I use this is a private repo where all contributors have write access

**Comment by ewjoachim** [comment]
> having both triggers means that the workflow runs twice for new commits added to an open pull request

If you look closely at the example I put above, you'll notice that when adding `pull_request`, I'm also restricting `push` to only happen on the `main` branch. So the CI only runs once when you push: either it's in a PR and it runs as part of the PR trigger, or you just merged a PR to `main`, which triggers the push. Of course, the idea is to put all your protected branches there.

**Comment by jarojasm95** [comment]
> > having both triggers means that the workflow runs twice for new commits added to an open pull request
> 
> If you look closely at the example I put above, you'll notice that when adding `pull_request`, I'm also restricting `push` to only happen on the `main` branch. So the CI only runs once when you push: either it's in a PR and it runs as part of the PR trigger, or you just merged a PR to `main`, which triggers the push. Of course, the idea is to put all your protected branches there.

Yep, I caught that, but then that means there's no CI run until a PR is opened.. which might not be ideal

Sorry if my use case seems too specific, I guess I am looking for a way to use this action to "build my own workflow" instead of adapting to the workflow suggested by this action.

**Comment by ewjoachim** [comment]
I was about to try and start working on that but...

If you push to a branch, the pull request may well not exist yet by the time the action finishes, so we can't post a comment to a non-existant PR ?

There's always the possibility of posting if there's a PR, and ignoring otherwise. Would that make a good UX ?

**Comment by jarojasm95** [comment]
> I was about to try and start working on that but...
> 
> If you push to a branch, the pull request may well not exist yet by the time the action finishes, so we can't post a comment to a non-existant PR ?
> 
> There's always the possibility of posting if there's a PR, and ignoring otherwise. Would that make a good UX ?

My "workaround" for that right now is the following:
```yaml
name: CI

on:
  push:
    branches:
      - "**"

jobs:
  # run all the lengthy and expensive tests and checks
  ########
  reports:
    name: reports
    runs-on: [self-hosted]
    permissions:
      pull-requests: write
      contents: write
      checks: write
    if: always()
    needs: init
    steps:
      - name: coverage data
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}
      ###########
      # upload coverage file to cloud storage
```

then on PR:
```yaml
name: PR

on:
  pull_request:
    branches-ignore:
      - dependabot/**

jobs:
  reports:
    name: reports
    runs-on: [self-hosted]
    needs: [init]
    permissions:
      checks: write
      contents: read
      pull-requests: write
    steps:
      # download coverage assuming ci job is done
      ####
      - name: coverage data
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}
          ANNOTATE_MISSING_LINES: true
```
