### ISSUE TITLE
Permission issue when creating comment

### ISSUE THREAD

**Issue by Mavtti** [py-cov-action/python-coverage-comment-action#518]
Hello, thanks a lot for the project, it's super useful ! 

I'm setting it up in a private repo and I'm getting permissions issues when the action tries to create the coverage comment.
Same as [this issue](https://github.com/py-cov-action/python-coverage-comment-action/issues/224).

```
Notice: Starting action
Notice: VERBOSE setting is deprecated. For increased debug output, see https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging
Notice: HTTP Request: GET https://api.github.com/repos/XXXX/MyRepo "HTTP/1.1 200 OK"
Notice: Generating comment for PR
Notice: HTTP Request: GET https://api.github.com/repos/XXXX/MyRepo/contents/data.json?ref=python-coverage-comment-action-data "HTTP/1.1 404 Not Found"
Notice: HTTP Request: GET https://api.github.com/user "HTTP/1.1 403 Forbidden"
Notice: HTTP Request: GET https://api.github.com/repos/XXXX/MyRepo/issues/241/comments "HTTP/1.1 [20](https://github.com/XXXX/MyRepo/actions/runs/13945192053/job/39030739680#step:5:21)0 OK"
Notice: Update previous comment
Notice: HTTP Request: PATCH https://api.github.com/repos/XXXX/MyRepo/issues/comments/27341[21](https://github.com/XXXX/MyRepo/actions/runs/13945192053/job/39030739680#step:5:22)134 "HTTP/1.1 200 OK"
Notice: Ending action
```

I'm following the doc for a matrix workflow with no external PR.

My workflow:
```yml
on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
   ...
   test:
    strategy:
      matrix:
        python-version: ["3.9.21", "3.10.16"]
     ...

   coverage:
    name: Coverage
    runs-on: ubuntu-latest
    needs: test
    permissions:
      pull-requests: write
      contents: write
```

Any idea what's wrong with my setup ?

thanks !
