### ISSUE TITLE
GITHUB_BASE_URL is not passed into dockerfile

### ISSUE THREAD

**Issue by PepijnB** [py-cov-action/python-coverage-comment-action#524]
in `action.yml` the `GITHUB_BASE_URL` is missing from the list environment variables that are set in the docker. 

For me this action does not work in GitHub enterprise environment. I believe this is the reason.

**Comment by ewjoachim** [comment]
Let's merge you PR and, yeah, find this bug :)

**Comment by ewjoachim** [comment]
Is it possible that you're putting your `GITHUB_BASE_URL` where it should be the base of the API, which should be (if I understand correctly) `https://<hostname>/api/v3/` ?

If so, do you want to make a PR making this explicit in the doc ?

**Comment by PepijnB** [comment]
I've updated the PR to include more info about the format of the `GITHUB_BASE_URL`. 

After the change, the login is successful, however now it complains about the wrong access rights. 
> Notice: Generating comment for PR
Error: Critical error. This error possibly occurred because the permissions of the workflow are set incorrectly. You can see the correct setting of permissions here: https://github.com/py-cov-action/python-coverage-comment-action#basic-usage
Otherwise please look for open issues or open one in https://github.com/py-cov-action/python-coverage-comment-action/

As experiment, I set my permissions as follows:
```yaml
permissions:
  # Gives the 'python-coverage-comment-action' action the necessary
  # permissions for publishing new comments in pull requests.
  pull-requests: write
  # Gives the 'python-coverage-comment-action' action the necessary
  # permissions for pushing data to the python-coverage-comment-action
  # branch, and for editing existing comments (to avoid publishing
  # multiple comments in the same PR)
  contents: write
  #FIXME: set all permissions to write --> !!just for testing purposes!! <--
  actions: write
  checks: write
  deployments: write
  issues: write
  packages: write
  repository-projects: write
  security-events: write
  statuses: write
```

I also swapped the `${{ github.token }}` with a PAT with full access. In both cases I get the same message. 
Do you have any idea what might be the reason for this?
