### ISSUE TITLE
Unrelated files may appear in comment

### ISSUE THREAD

**Issue by stickperson** [py-cov-action/python-coverage-comment-action#529]
The [diff calculation](https://github.com/py-cov-action/python-coverage-comment-action/blob/ffd1aa12992c2272b950cc6c882674e0c07bc8e8/coverage_comment/coverage.py#L296) is similar to the [two dot diff comparison](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-comparing-branches-in-pull-requests#three-dot-and-two-dot-git-diff-comparisons) and can result in files unrelated to a PR appearing in the coverage comment. This can happen if there is a merge to the base ref or default branch between the time the GHA was kicked off and this action is run.

I _think_ this is a bug and not the desired result.

**Comment by ewjoachim** [comment]
Oh, you're probably right, it's a bug! Do you want to make a PR ?

**Comment by stickperson** [comment]
Sure, I can get to it today.

**Comment by stickperson** [comment]
This actually may be more complicated than originally planned. I actually think `git fetch origin main --depth=1000` is not doing anything _unless_ `actions/checkout@v4` is using `fetch-depth: 1000` (or 0). This GHA illustrates the point:


```
name: CI

on:
  pull_request:
concurrency:
  group: ${{ github.event_name }}-${{ github.ref }}

jobs:
  fetch_depth:
    name: Fetch all history
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch base branch
        run: git fetch origin main --depth=1000
      - name: diff
        run: git diff -U0 FETCH_HEAD...
  no_fetch_depth:
    name: Fetch single commit
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Fetch base branch
        run: git fetch origin main --depth=1000
      - name: diff
        run: git diff -U0 FETCH_HEAD...
```

In `no_fetch_depth`, `git diff -U0 FETCH_HEAD...` fails with `fatal: FETCH_HEAD...HEAD: no merge base`. So I believe the actual fix is:

- remove the [git.fetch](https://github.com/py-cov-action/python-coverage-comment-action/blob/main/coverage_comment/coverage.py#L295) call since it will not do anything
- update the diff command
- instruct users to set `fetch-depth: 1000` in the `actions/checkout`

Just double checking that sounds right before I go ahead and put up a fix.
